### ISSUE TITLE
Can it be compatible with OreDictionary

### ISSUE THREAD

**Issue by AmalaNever** [PIPPIP5789/MFREx#1]
Thank you for your great work!!
In the actual operation process，I found Carpenter may used OreDictionary to crafting items, but i found the code below where is “item” and  “ItemStack” , not “ore” and “IIngredient”? But it only Blast Furnace code, I haven't found the code for Carpenter.
I don't quite understand this part, and not sure if it's difficult to implement it. Thank you for your help!
The code: 
/*
       {
            "type": "BlastFurnaceRecipe",
            "input": {
                "item": "minecraft:sand"
            },
            "result": {
                "item": "minefantasyreforged:salt"
            }
       }
     */
protected void parse(String name, JsonObject json) {
        String type = JsonUtils.getString(json, "type");
        ItemStack inputStack = deserializeIngredient(JsonUtils.getJsonObject(json, "input")).getMatchingStacks()[0];
        ItemStack resultStack = deserializeIngredient(JsonUtils.getJsonObject(json, "result")).getMatchingStacks()[0];

[#src/main/java/com/PIPPIP5789/mfrex/recipe/BlastFurnaceRecipeLoader.java]

**Comment by PIPPIP5789** [comment]
Thank you for playing the mod!

With how Minecraft handles the OreDict, this should have ore and ingredient compatibility built-in; the deserializeIngredient should handle that, to my knowledge. Have you tried creating a recipe that uses something like "ore:ironIngot" instead of "minecraft:iron_ingot"? (Note: I don't know if those are actual examples... I'd do research to make sure the OreDict exists before trying it). If for whatever reason it doesn't work, please let me know what's not working, and I can look into it.

**Comment by AmalaNever** [comment]
> Thank you for playing the mod!
> 
> With how Minecraft handles the OreDict, this should have ore and ingredient compatibility built-in; the deserializeIngredient should handle that, to my knowledge. Have you tried creating a recipe that uses something like "ore:ironIngot" instead of "minecraft:iron_ingot"? (Note: I don't know if those are actual examples... I'd do research to make sure the OreDict exists before trying it). If for whatever reason it doesn't work, please let me know what's not working, and I can look into it.

I haven't tried such recipes yet. I will try it and let you know the results. Thank you for your reply！

**Comment by AmalaNever** [comment]
I have tried some writing methods and reported errors: 
When I define an item below
The iron ingot oredict: <ore:ingotIron>
"ore": "ingotIron", "data": 0     crash reason: reportedMissing item, expected to find a string
"item": "ore:ingotIron", "data": 0    crash reason: Unable to find entry with registry name "ore:ironIngot"
"item": "ore:ingotIron"       crash reason: Unable to find entry with registry name "ore:ironIngot"
"ores": "ingotIron", "data": 0      crash reason: Missing item, expected to find a stringMissing item, expected to find a string
"ore": "ingotIron"  crash reason: Missing item, expected to find a string
The crash-reports:
[crash-2023-05-23_01.18.01-client.txt](https://github.com/PIPPIP5789/MFREx/files/11534515/crash-2023-05-23_01.18.01-client.txt)
[crash-2023-05-23_01.20.21-client.txt](https://github.com/PIPPIP5789/MFREx/files/11534516/crash-2023-05-23_01.20.21-client.txt)
[crash-2023-05-23_01.22.03-client.txt](https://github.com/PIPPIP5789/MFREx/files/11534517/crash-2023-05-23_01.22.03-client.txt)
[crash-2023-05-23_01.23.54-client.txt](https://github.com/PIPPIP5789/MFREx/files/11534518/crash-2023-05-23_01.23.54-client.txt)
[crash-2023-05-23_01.26.27-client.txt](https://github.com/PIPPIP5789/MFREx/files/11534519/crash-2023-05-23_01.26.27-client.txt)
[crash-2023-05-23_01.28.16-client.txt](https://github.com/PIPPIP5789/MFREx/files/11534520/crash-2023-05-23_01.28.16-client.txt)
[crash-2023-05-23_01.29.21-client.txt](https://github.com/PIPPIP5789/MFREx/files/11534521/crash-2023-05-23_01.29.21-client.txt)
[crash-2023-05-23_01.30.39-client.txt](https://github.com/PIPPIP5789/MFREx/files/11534522/crash-2023-05-23_01.30.39-client.txt)

And my correct recipes: had mods forestry and futuremc
{ 
    "type": "crafting_shaped", 
    "skill": "none", "research": "", 
    "tool_type": "hammer", 
    "is_tool_recipe": false, 
    "block_tier": -1, 
    "craft_time": 10, 
    "tool_tier": -1, 
    "experience": 0, 
    "sound": "minefantasyreforged:block.hammercarpenter", 
    "pattern": [ " a  ", "aba ", "ccc ", "    " ], 
    "key": 
    { 
        "a": 
        { 
            "item": "minefantasyreforged:timber", "data": 0
        } ,
        "b": 
        { 
            "item": "minecraft:coal", "data": 0
        } ,
        "c": 
        { 
            "item": "forestry:wood_pile", "data": 0
        } 
    }, 
    "result": 
    { 
        "item": "futuremc:campfire" 
    } 
}
![2023-05-23_01 40 38](https://github.com/PIPPIP5789/MFREx/assets/30771941/de1883fb-8bb5-411e-b830-2939d9100231)
![2023-05-23_01 40 18](https://github.com/PIPPIP5789/MFREx/assets/30771941/0177d357-12e4-43fc-bbc6-0a8ffd64a7db)

**Comment by PIPPIP5789** [comment]
Since MFR has finished the first part of the Data Driven Update, this part of the mod is redundant and will be removed, so... not much more help I can be here. Closing this due to that.

And ofc, the DDU has OreDict support, so no worries there
